---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      project: roboshop
  template:
    metadata:
      labels:
        app: frontend
        project: roboshop
    spec:
      volumes:
        - name: configs
          configMap:
            name: nginx-conf
      containers:
        - name: nginx
          image: rkalluru/d51-frontend:VERSION
          volumeMounts:
            - name: configs
              mountPath: /opt/nginx
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: roboshop
  ports:
    - port: 80
      targetPort: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen       80;
            server_name  localhost;

            proxy_http_version 1.1;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                ssi    on;
            }

            location /images/ {
                expires 5s;
                root   /usr/share/nginx/html;
                try_files $uri /images/placeholder.jpg;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            location /api/catalogue/ {
                proxy_pass http://catalogue-svc:8000/;
            }

            location /api/user/ {
                proxy_pass http://user-svc:8000/;
            }

            location /api/cart/ {
                proxy_pass http://cart-svc:8000/;
            }

            location /api/shipping/ {
                proxy_pass http://shipping-svc:8000/;
            }

            location /api/payment/ {
                proxy_pass http://payment-svc:8000/;
            }

            location /nginx_status {
                stub_status on;
                access_log off;
            }
        }

    }
