---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      project: roboshop
  template:
    metadata:
      labels:
        app: cart
        project: roboshop
    spec:
      containers:
        - name: cart
          image: rkalluru/d51-cart:VERSION
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-master.db.svc.cluster.local
            - name: CATALOGUE_HOST
              value: catalogue-svc
---
kind: Service
apiVersion: v1
metadata:
  name: cart-svc
spec:
  selector:
    app: cart
    project: roboshop
  ports:
    - port: 8000
      targetPort: 8000
