---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      project: roboshop
  template:
    metadata:
      labels:
        app: payment
        project: roboshop
    spec:
      containers:
        - name: payment
          image: rkalluru/d51-payment:VERSION
          ports:
            - containerPort: 8000
          env:
            - name: CART_HOST
              value: cart-svc
            - name: USER_HOST
              value: user-svc
            - name: AMQP_HOST
              value: rabbitmq.db.svc.cluster.local
            - name: AMQP_USER
              value: roboshop
            - name: AMQP_PASS
              value: roboshop123
---
kind: Service
apiVersion: v1
metadata:
  name: payment-svc
spec:
  selector:
    app: payment
    project: roboshop
  ports:
    - port: 8000
      targetPort: 8000
