kind: Pod
apiVersion: v1
metadata:
  name: pod05
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "10000"
      env:
        - name: URL
          value: google.com
